# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

### Send POST request with json body
POST http://127.0.0.1:8000/submit/map
Content-Type: application/json

{
  "map_code": "JEZAT",
  "map_type": ["Framework"],
  "map_name": "Hanamura",
  "desc": "Fake uppercut OW2",
  "creators": [0, 1, 2]
}

###
